### ISSUE TITLE
Seed zero not cycling through results? (was: Normal Increment - instead of Random)

### ISSUE THREAD

**Issue by enzyme69** [chrisgoringe/cg-random#1]
I like this custom node, allowing ComfyUI to randomly pick LoRA and images from folder. But I wonder why we don't have sequential order as well? The random is nice, and the seed increment or random is good to, but I need just a basic sequence of image loading.

Any possibility to have this option?

**Comment by chrisgoringe** [comment]
From the readme:

- If the seed is set to `0`, the loader will cycle systematically through the options instead of being random.

Is that not what you want?

**Comment by enzyme69** [comment]
Yes, I am aware of increment on seed. But still I am getting random. Just need a sequential images inside a folder, for batch.

I tried using multiple of this node, with folder with numbered image sequence, but somewhat the image loaded in not in sequence. I test it with image preview, and each node is giving a random image, instead of just simply loading it in sequence, which will go up 1 increment after each queue (automatic).

**Comment by chrisgoringe** [comment]
OK, if seed=0 isn't cycling through the images systematically that's a bug. I've changed the title and will check when I can...

**Comment by chrisgoringe** [comment]
Oops. That's an error in the documentation. You don't use seed = 0, you set mode to 'iterative' then it will cycle through the images in the folder.

![GIF 8-12-2023 11-05-31 AM](https://github.com/chrisgoringe/cg-random/assets/4371971/6dae8787-f349-410c-b052-c1660d94c799)

**Comment by enzyme69** [comment]
Yeah, it is random, but I have sequence of images, numbered, I wish it does not random, but just iterate sequentially. Because ComfyUI does not have this.
https://github.com/chrisgoringe/cg-random/assets/3952687/32fc26cf-1554-46a2-8240-8430bd8a8d5c

**Comment by chrisgoringe** [comment]
If You set the mode to iterative it isn't random.

**Comment by enzyme69** [comment]
https://github.com/chrisgoringe/cg-random/assets/3952687/52820f46-e2cd-4748-9f0f-705b4fd49829

But look how my budgie is jumping around. Original sequence PNG is not like that.

**Comment by chrisgoringe** [comment]
How are the PNG files named?

**Comment by chrisgoringe** [comment]
OK, the use of seed=0 has been removed - now you specify random or systematic. Closing this, please open a new ticket if there is still a problem
